// <auto-generated />
using System;
using AutoParts.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AutoParts.Api.Data.Migrations
{
    [DbContext(typeof(AutoPartsDbContext))]
    [Migration("20260910014305_SeedEngineDemoPriceRange")]
    partial class SeedEngineDemoPriceRange
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.3");

            modelBuilder.Entity("AutoParts.Api.Models.CompatibilityReviewLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("NewRelevance")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NewStatus")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<int>("PartCompatibilityId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("PerformedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("PerformedByUserId")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int?>("PreviousRelevance")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("PreviousStatus")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PartCompatibilityId", "PerformedAt");

                    b.ToTable("CompatibilityReviewLogs");
                });

            modelBuilder.Entity("AutoParts.Api.Models.ImportRun", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("FinishedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("RecordsProcessed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ImportRuns");
                });

            modelBuilder.Entity("AutoParts.Api.Models.Part", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Applications")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("CatalogDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("KeywordGroup")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("OemPartNumber")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Position")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Side")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("SuggestedValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("SupersededByPartNumber")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("OemPartNumber")
                        .IsUnique();

                    b.HasIndex("Position");

                    b.HasIndex("Side");

                    b.ToTable("Parts");
                });

            modelBuilder.Entity("AutoParts.Api.Models.PartCompatibility", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Confidence")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("ConfirmedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ConfirmedByUserId")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("EvidenceText")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<int>("PartId")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly?>("ProductionEnd")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("ProductionStart")
                        .HasColumnType("TEXT");

                    b.Property<int>("Relevance")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("VehicleId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("VehicleId");

                    b.HasIndex("PartId", "Status", "Relevance");

                    b.HasIndex("PartId", "VehicleId", "ProductionStart")
                        .IsUnique();

                    b.ToTable("PartCompatibilities");
                });

            modelBuilder.Entity("AutoParts.Api.Models.PartPriceObservation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Amount")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsSample")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("ObservedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("PartId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PartId", "ObservedAt");

                    b.ToTable("PartPriceObservations");
                });

            modelBuilder.Entity("AutoParts.Api.Models.Vehicle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Chassis")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Engine")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Manufacturer")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Market")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<int>("MarketRelevance")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MarketRelevanceSource")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("MarketRelevanceUpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("ModelYear")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly?>("ProductionDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("SerialNumber")
                        .HasMaxLength(7)
                        .HasColumnType("TEXT");

                    b.Property<string>("TypeCode")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Vin")
                        .HasMaxLength(17)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SerialNumber")
                        .IsUnique();

                    b.HasIndex("Vin")
                        .IsUnique();

                    b.HasIndex("Manufacturer", "Model", "Chassis", "Engine", "TypeCode");

                    b.ToTable("Vehicles");
                });

            modelBuilder.Entity("AutoParts.Api.Models.CompatibilityReviewLog", b =>
                {
                    b.HasOne("AutoParts.Api.Models.PartCompatibility", "PartCompatibility")
                        .WithMany("ReviewLogs")
                        .HasForeignKey("PartCompatibilityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PartCompatibility");
                });

            modelBuilder.Entity("AutoParts.Api.Models.PartCompatibility", b =>
                {
                    b.HasOne("AutoParts.Api.Models.Part", "Part")
                        .WithMany("Compatibilities")
                        .HasForeignKey("PartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AutoParts.Api.Models.Vehicle", "Vehicle")
                        .WithMany("Compatibilities")
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Part");

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("AutoParts.Api.Models.PartPriceObservation", b =>
                {
                    b.HasOne("AutoParts.Api.Models.Part", "Part")
                        .WithMany("PriceObservations")
                        .HasForeignKey("PartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Part");
                });

            modelBuilder.Entity("AutoParts.Api.Models.Part", b =>
                {
                    b.Navigation("Compatibilities");

                    b.Navigation("PriceObservations");
                });

            modelBuilder.Entity("AutoParts.Api.Models.PartCompatibility", b =>
                {
                    b.Navigation("ReviewLogs");
                });

            modelBuilder.Entity("AutoParts.Api.Models.Vehicle", b =>
                {
                    b.Navigation("Compatibilities");
                });
#pragma warning restore 612, 618
        }
    }
}
